"""Insert test rows with sensible defaults; override only what a test cares about."""

import json
from datetime import datetime, timedelta

BARTER = {
    "Title": "Tennis Group Class",
    "PartnerBrandName": "Kallang Tennis Centre",
    "Category": "Sport",
    "Subcategory": "Tennis",
    "HeroImageURL": "https://images.example/tennis.jpg",
    "AboutExperience": "A group tennis class.",
    "CompensationType": "Barter",
    "BarterDescription": "Complimentary group tennis class (1 hour)",
    "CollaborationType": "One-off",
    "DeliverableType": "Fixed",
    "ExperienceSkillLevel": "Beginner,Intermediate",
    "AreaNeighbourhood": "Kallang",
    "VenueName": "Kallang Tennis Centre",
    "FullAddress": "Stadium Road, Singapore 397630",
    "PublishingStatus": "Live",
}

PAID = {
    **BARTER,
    "Title": "Activewear Campaign",
    "PartnerBrandName": "FullOut Activewear",
    "Category": "Lifestyle",
    "Subcategory": "Activewear",
    "CompensationType": "Paid",
    "BarterDescription": None,
    "PaidCurrency": "SGD",
    "PaidAmount": 150,
    "PaidPaymentBasis": "Flat fee",
    "PaidCompensationNote": "Plus an activewear set to keep",
    "AreaNeighbourhood": "Tanjong Pagar",
}


def _insert(conn, table, row):
    columns = ", ".join(row)
    placeholders = ", ".join(["%s"] * len(row))
    cursor = conn.cursor()
    cursor.execute(f"INSERT INTO {table} ({columns}) VALUES ({placeholders})", list(row.values()))
    conn.commit()
    return cursor.lastrowid


def add_opportunity(conn, base=BARTER, **columns):
    return _insert(conn, "Opportunity", {**base, **columns})


def add_session(conn, opportunity_id, starts_at: datetime, *, slots=3, cancelled=False, recurrence_id=None):
    """A one-off Session, or one generated by the Recurring Schedule `recurrence_id`."""
    ends_at = starts_at + timedelta(hours=1)
    return _insert(conn, "Session", {
        "OpportunityID": opportunity_id,
        "SessionDate": starts_at.date(),
        "StartTime": starts_at.time(),
        "EndTime": ends_at.time(),
        "CreatorSlots": slots,
        "IsCancelled": cancelled,
        "RecurrenceID": recurrence_id,
    })


def add_schedule(conn, opportunity_id, first_starts_at: datetime, *, slots=3):
    """A weekly Recurring Schedule with no End Date; add its Sessions with `add_session(recurrence_id=...)`."""
    return _insert(conn, "RecurringSchedule", {
        "OpportunityID": opportunity_id,
        "StartDate": first_starts_at.date(),
        "EndDate": None,
        "DayFrequency": "Weekly",
        "StartTime": first_starts_at.time(),
        "EndTime": (first_starts_at + timedelta(hours=1)).time(),
        "DefaultCreatorSlots": slots,
    })


def add_deliverable(conn, opportunity_id, text):
    return _insert(conn, "DeliverableItems", {"OpportunityID": opportunity_id, "ItemDescription": text})


def add_info(conn, opportunity_id, label, value):
    return _insert(conn, "AdditionalInformation", {
        "OpportunityID": opportunity_id, "Label": label, "Value": value,
    })


def add_application(conn, opportunity_id, session_id, *, status="New"):
    return _insert(conn, "Application", {
        "OpportunityID": opportunity_id,
        "OriginalSessionID": session_id,
        "CurrentSessionID": session_id,
        "Status": status,
        "FullName": "Test Creator",
        "InstagramHandle": "testcreator",
        "EmailAddress": "creator@example.com",
        "MobileWhatsAppNumber": "+65 9123 4567",
        "SubmissionSnapshot": json.dumps({}),
    })
